let shopItemsData = [{
    id:"buyfromme",
    name: "Extra Soft",
    price: 2500,
    desc: "lorem7",
    img: "./assets/1stproduct.png",
},
{
    id:"woman",
    name: "Doctor's Pad",
    price: 6000,
    desc: "lorem7",
    img: "./assets/1stproduct.png",
},
{
    id:"mann",
    name: "Orthopedic Pad",
    price: 2000,
    desc: "lorem7",
    img: "./assets/3rdpic.png",
},
{
    id:"getfrome",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set8",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set7",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set6",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set5",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set4",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set3",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set2",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
{
    id:"set1",
    name: "comfort pad",
    price: 7000,
    desc: "lorem7",
    img: "./assets/doctor-extra-soft-navy-thong-orthopaedic-thong-strap-flip-flops.png",
},
];
